### ISSUE TITLE
can not write a single bit by S7multivar.read()

### ISSUE THREAD

**Issue by blanaa** [fbarresi/Sharp7#12]
I tried to use S7multivsr to write a single bit into a PLC, but it aways outputs an error code:0x01400000.

**Comment by fbarresi** [comment]
Hi, 
This error code is defined [here](https://github.com/fbarresi/Sharp7/blob/15294d28ce5731e54fe66125354de9e86c684e7c/Sharp7/S7Consts.cs#L48) and means that your CPU does not support this of function.

That's all I can tell you about this error.
Please clarify if your CPU has such a capability or try writing whole bytes instead of bits.

Kind regards,
fbarresi

**Comment by jingweiwu** [comment]
Hi, 
On this issue, I have another question: Is there an approach to figure out whether the CPU on hand (S7-300/400 series for example) supports this function or not before reading or writing operation s?

**Comment by fbarresi** [comment]
Hi,
I'm really not sure if it would work, but I will give a try with the method [GetCpuInfo](https://github.com/fbarresi/Sharp7/wiki/System-information-functions#getcpuinfo).

**Comment by jingweiwu** [comment]
> 
> 
> Hi,
> I'm really not sure if it would work, but I will give a try with the method [GetCpuInfo](https://github.com/fbarresi/Sharp7/wiki/System-information-functions#getcpuinfo).

Thanks! ;-)
